### ISSUE TITLE
Getting ActionGeo into a map

### ISSUE THREAD

**Issue by ianks** [CSCI-4830-002-2014/challenge-week-7#15]
For some reason, ActionGeo will not allow me to throw it on a map. Any clues?

![image](https://www.dropbox.com/s/ljx6ft8kxb2gxok/Screenshot%202014-10-12%2021.38.45.png?dl=1)

**Comment by indiesquidge** [comment]
First off, under the `Measures` category, choose the carrot when hovered over `ActionGeo Long`, then go to `Geographic Role`, and check `Longitude`. This will change the symbol next to the type from a `#` to a globe (like `ActionGeo Lat`).

Then, once you have your columns and rows set, change both from a `Measure` to a `Dimension`. This should make a map show up.

**Comment by ianks** [comment]
Excellent. Thank you sir :beers:
