### ISSUE TITLE
Dimensions and Measure Field Names Not in the Data Extract

### ISSUE THREAD

**Issue by nikitavoskoboynik** [CSCI-4830-002-2014/challenge-week-7#17]
I downloaded the previous days csv file, but when I import to data into tableau, the columns have no names. Do I have to manually name all the fields? The instructions for the checkpoint simply say to import the data. Would really appreciate some help. Thank You.

**Comment by nikitavoskoboynik** [comment]
![screen shot 2014-10-12 at 10 22 02 pm](https://cloud.githubusercontent.com/assets/8550866/4608964/8a131d40-5290-11e4-92c9-6c8f5bef4a80.png)

This is what I am getting...

**Comment by wannabeCitizen** [comment]
There is already an issue that solves this.
